### ISSUE TITLE
请求添加支持Docker部署

### ISSUE THREAD

**Issue by spysir** [xxss0903/drawstamputils#3]
请求添加支持Docker部署，谢谢

**Comment by wanghuangjie** [comment]
mkdir drawstamp
cd drawstamp 
git clone https://github.com/xxss0903/drawstamputils.git
nano Dockerfile
```
FROM node:20
WORKDIR /app
COPY ./drawstamputils/*.json ./
RUN npm install
COPY ./drawstamputils ./
CMD ["npm", "install"]
```
nano docker-compose.yaml
```
version: "2"
services:
  drawstamp:
    build: .
    working_dir: /app
    environment:
      - NODE_ENV=production
    volumes:
      - ./drawstamputils:/app
      - /app/node_modules

    ports:
      - "5173:5173"
    command: "npm run dev -- --host 0.0.0.0"
```

docker-compose up -d
